---

# Переменные которые объявляются для отработки функционала модуля

vboxguest_iso: ""
vboxguest_url: ""

# Разрешено ли удалять, если версия отличается
vboxguest_remove: False

# Требуемая версия
vboxguest_version: no
